pipeline:
  agent:
    label: any

  stages:
    - stage: Checkout
      steps:
        - checkout scm

    - stage: Build
      steps:
        - sh 'mvn clean package -DskipTests'

    - stage: Archive WAR
      steps:
        - archiveArtifacts:
            artifacts: "target/*.war"
            fingerprint: true
